Vagrant.configure("2") do |config|

  config.vm.define :dovcot_build do |instance|
    instance.vm.box = "centos-6.6-x86_64"
  end

  config.vm.provider :libvirt do |libvirt|
     libvirt.driver = "kvm"
     libvirt.host = "bonaire.oetiker.ch"
     libvirt.username = "moetiker_adm"
     libvirt.id_ssh_key_file = "/home/moetiker/.ssh/id_rsa_4096_admin"
     libvirt.uri =
     "qemu+ssh://moetiker_adm@bonaire:46022/system?keyfile=/home/moetiker/.ssh/id_rsa_4096_admin&amp;netcat=sudo%20nc"
     libvirt.connect_via_ssh = true
  end

end
